credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Administrator
      password: $2b$12$m7034LzAjbi6imDIWMGFA.942hzkr1NpwzPd2UgOmOJ6M12YEkIx2
cookie:
  expiry_days: 30
  key: some_signature_key_12345
  name: some_cookie_name
